### ISSUE TITLE
lack of timeout messages

### ISSUE THREAD

**Issue by dowcet** [tokland/pysheng#18]
If a download fails for a certain page, does Pysheng simply try the next page, after a certain period of time? Without any messages it's unclear what's happening.

I had a download hang for at least ten minutes with no messages, so I finally hit Control-C. Here is the output. 
```
^CTraceback (most recent call last):
  File "/usr/local/bin/pysheng", line 6, in <module>
    sys.exit(pysheng.main(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/pysheng/download.py", line 149, in main
    for page_info, page, image_data in download_book(url, options.page_start, options.page_end):
  File "/usr/local/lib/python2.7/dist-packages/pysheng/download.py", line 125, in download_book
    image_data = download(image_url, opener=opener)
  File "/usr/local/lib/python2.7/dist-packages/pysheng/download.py", line 104, in download
    return lib.download(*args, **dict(kwargs, agent=AGENT))
  File "/usr/local/lib/python2.7/dist-packages/pysheng/lib.py", line 57, in download
    return opener.open(request).read()
  File "/usr/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 567, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
KeyboardInterrupt
```
It would be nice if pysheng could recognize that downloads aren't working and at least throw a warning or something, and maybe allow the user to exit more gracefully. 

(If I can figure out how to address any of the issues I am posting about, I will try to make a pull request.)

**Comment by tokland** [comment]
I am not adding new code, just fixing important bugs. Pull requests welcome.

**Comment by dowcet** [comment]
OK, thanks. I'll see if I can figure it out.
